version: '3'

x-hub-registry-common: &registry
  image: registry:2
  expose:
    - "5000"
  environment:
    #REGISTRY_AUTH: htpasswd
    #REGISTRY_AUTH_HTPASSWD_REALM: Registry
    #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    #- ./auth:/auth
    - data:/data
    - ./configs/registry-config.yml:/etc/docker/registry/config.yml

services:
  registry-1:
    <<: *registry
    container_name: registry-1
    hostname: registry-1

  registry-2:
    <<: *registry
    container_name: registry-2
    hostname: registry-2

  registry-3:
    <<: *registry
    container_name: registry-3
    hostname: registry-3

  registry-4:
    <<: *registry
    container_name: registry-4
    hostname: registry-4
    ports:
      - "9208:5000"

  registry-5:
    <<: *registry
    container_name: registry-5
    hostname: registry-5
    ports:
      - "5001:5001"
      - "9201:5001"
    volumes:
      - ./configs/elastic-config.yml:/etc/docker/registry/config.yml

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    hostname: nginx
    ports:
      - "5000:5000"
      - "9200:5000"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registry-1
      - registry-2
      - registry-3
      - registry-4

volumes:
  data:
    name: docker-registry
