version: '3.9'

x-registry-common: &registry-common
  image: registry:2
  restart: unless-stopped
  expose:
    - "5000"
  environment:
    #REGISTRY_AUTH: htpasswd
    #REGISTRY_AUTH_HTPASSWD_REALM: Registry
    #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data

x-proxy-registry: &proxy-registry-common
  <<: *registry-common
  volumes:
    #- ./auth:/auth
    - data:/data
    - ./configs/registry-config.yml:/etc/docker/registry/config.yml

services:
  proxy-registry-1:
    <<: *proxy-registry-common
    container_name: proxy-registry-1
    hostname: registry-1

  proxy-registry-2:
    <<: *proxy-registry-common
    container_name: proxy-registry-2
    hostname: registry-2

  proxy-registry-3:
    <<: *proxy-registry-common
    container_name: proxy-registry-3
    hostname: registry-3

  proxy-registry-4:
    <<: *proxy-registry-common
    container_name: proxy-registry-4
    hostname: registry-4

  ai-registry:
    <<: *registry-common
    container_name: ai-registry
    hostname: registry
    ports:
      - "9200:5000"
    volumes:
      #- ./auth:/auth
      - data:/data

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    hostname: nginx
    ports:
      - "9201:5000"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - proxy-registry-1
      - proxy-registry-2
      - proxy-registry-3
      - proxy-registry-4

volumes:
  data:
    name: docker-registry
