version: '3'

services:
  hub-cache-1:
    image: registry:2
    container_name: hub-cache-1
    hostname: hub-cache-1
    expose:
      - "5000"
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
            #- ./auth:/auth
      - ./data:/data
      - ./configs/hub-cache-config.yml:/etc/docker/registry/config.yml

  hub-cache-2:
    image: registry:2
    container_name: hub-cache-2
    hostname: hub-cache-2
    expose:
      - "5000"
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
            #- ./auth:/auth
      - ./data:/data
      - ./configs/hub-cache-config.yml:/etc/docker/registry/config.yml

  hub-cache-3:
    image: registry:2
    container_name: hub-cache-3
    hostname: hub-cache-3
    expose:
      - "5000"
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
            #- ./auth:/auth
      - ./data:/data
      - ./configs/hub-cache-config.yml:/etc/docker/registry/config.yml

  hub-cache-4:
    image: registry:2
    container_name: hub-cache-4
    hostname: hub-cache-4
    expose:
      - "5000"
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
            #- ./auth:/auth
      - ./data:/data
      - ./configs/hub-cache-config.yml:/etc/docker/registry/config.yml

  elastic-cache-1:
    image: registry:2
    container_name: elastic-cache-1
    hostname: elastic-cache-1
    expose:
      - "5000"
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
            #- ./auth:/auth
      - ./data:/data
      - ./configs/elastic-cache-config.yml:/etc/docker/registry/config.yml

  elastic-cache-2:
    image: registry:2
    container_name: elastic-cache-2
    hostname: elastic-cache-2
    expose:
      - "5000"
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
            #- ./auth:/auth
      - ./data:/data
      - ./configs/elastic-cache-config.yml:/etc/docker/registry/config.yml

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    hostname: nginx
    ports:
      - "5000:5000"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hub-cache-1
      - hub-cache-2
      - hub-cache-3
      - hub-cache-4
      - elastic-cache-1
      - elastic-cache-2
